# Generated by Django 4.0.1 on 2023-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '3. Action',
            },
        ),
        migrations.AddConstraint(
            model_name='name',
            constraint=models.UniqueConstraint(fields=('username', 'amount', 'price'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='name',
            constraint=models.UniqueConstraint(condition=models.Q(('price', None)), fields=('username', 'amount'), name='unique_without_optional'),
        ),
    ]
